#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


surfaceGenerateBoundingBox vortex_generator_rocket.stl vortex_generator_rocket_box.stl 2 2 15 5 2 2
runApplication cartesianMesh
runApplication checkMesh -constant
