#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

surfaceGenerateBoundingBox rocket.stl rocket_box.stl 1 1 1 1 15 5
runApplication cartesianMesh
runApplication checkMesh -constant
