#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


surfaceGenerateBoundingBox rocket.stl rocket_box.stl 1.5 1.5 4 4 20 20
runApplication cartesianMesh
runApplication checkMesh -constant
