#!/bin/sh

VARS=`ls logs | grep FinalRes | sed -e 's/FinalRes_0//'`
DIR=logs

PLOT=""
HEAD=1

for VAR in $VARS ; do
    if [ -e "logs/${VAR}_0" ] ; then
        if [ $HEAD -eq 1 ] ; then
            PLOT="plot 'logs/${VAR}_0' title '$VAR' w l"
            HEAD=0
        else
            PLOT="$PLOT, 'logs/${VAR}_0' title '$VAR' w l"
        fi
    fi
done

gnuplot -p <<EOF
set title 'Residuals'
set xlabel 'Time'
set ylabel 'Initial residual'
set logscale y
set format y "%.0e"
set grid

$PLOT
set terminal pngcairo size 1600,900
set output 'residual.png'
replot
EOF

#------------------------------------------------------------------------------
